### ISSUE TITLE
Android R (11) 没有显示气泡

### ISSUE THREAD

**Issue by LIUYOU2015** [Jeasoon/BubbleKit#1]
您好，我在Pixel_3a_API_30_x86运行了您的项目，效果如下，没有显示气泡的效果，请问在Android R上需要什么特殊的配置吗？（Bubbles已开）
![image](https://user-images.githubusercontent.com/32282247/88307500-9b932680-cd3e-11ea-81b1-b0c3168b976b.png)
![image](https://user-images.githubusercontent.com/32282247/88307652-cd0bf200-cd3e-11ea-83c1-18edaf7684b5.png)

**Comment by Jeasoon** [comment]
我当时写这个demo的时候是基于Q版本和较早的R版本, 最近几个月源码和使用方式可能又有了新的更改. Demo部分气泡功能可能不适用了. 但是我使用 Pixel 3XL, 本地效果还是可以弹出来的. 可能你本地有些开关没有打开, 可以按照如下步骤操作试试:
1. 开发者选项 -> 对话泡(页面滑到最后, "应用"这个分类最后一个) -> 打开开关
2. 长按气泡应用图标 -> 点击"应用信息"-> 通知 -> 点击"对话泡" -> 选择"所有对话都能以对话泡形式展示"

![screen1](https://user-images.githubusercontent.com/17696727/88453265-fb511500-ce97-11ea-8c5d-5df78007a813.png)
![screen2](https://user-images.githubusercontent.com/17696727/88453268-ff7d3280-ce97-11ea-9244-e9026837c14b.png)
![screen3](https://user-images.githubusercontent.com/17696727/88453269-0146f600-ce98-11ea-94c3-899dccc14653.png)

**Comment by LIUYOU2015** [comment]
感谢您的回复，我用的是pixel 4 Android 11 的版本，这一步

> 长按气泡应用图标 -> 点击"应用信息"-> 通知 -> **点击"对话泡"** -> 选择"所有对话都能以对话泡形式展示"

没有对话泡的选项（Messager app 有），不过我Android 11的版本开启气泡已经不在开发者模式里了，在 setting -> app&notification里，方便告知您系统的具体版本吗？

**Comment by Jeasoon** [comment]
我刷的系统版本为 android 11 预览版, 按照我在2楼回复的方法, 是可以正常显示气泡的
刷机地址: [https://developer.android.google.cn/preview/download](https://developer.android.google.cn/preview/download)
系统版本:
![screen](https://user-images.githubusercontent.com/17696727/88456198-4f66f400-ceae-11ea-8ef6-85293738155c.png)
